events:
  kill-wither:
    type: KILL
    value: "entity:wither;"
    cancel-real: true
    conditions:
      1:
        value: "type:SHIFTING;value:true;"
    rewards:
      give:
        type: COMMAND
        value: "give %player% nether_star"
      item:
        type: ITEM
        value: "sharded-emerith"
      add:
        type: STORAGE
        value: "identifier:kill-wither;value:+1;"

items:
  looted-emerith:
    value: "material:emerald;amount:%random1,%random3,5%%;name:&7&k..&r &5&lSharded &2&lEmerith&r &7&k..;tags:shopItem:yes,serverItem:yes;"
  sharded-emerith:
    value: "material:emerald;amount:1;name:&7&k..&r &5&lSharded &2&lEmerith&r &7&k..;tags:shopItem:yes,serverItem:yes;"
