events:
  kill-wither:
    type: KILL
    value: "entity:wither;"
    cancel-real: true
    conditions:
      1:
        value: "type:SHIFTING;value:true;"
      2:
        value: "type:BLOCK_EQUALS;value:true,0,-1,0,bedrock;"
      3:
        value: "type:ITEM_COUNT;value:1,@;"
      4:
        value: "type:ITEM_COUNT;value:1,0;"
      5:
        value: "type:ITEM_TAG;value:shopItem,true;"
    rewards:
      give:
        type: COMMAND
        value: "give %player% nether_star"
      item:
        type: ITEM
        value: "wither-shard"
      add:
        type: STORAGE
        value: "identifier:kill-wither;value:+1;"

items:
  wither-shard:
    value: "material:emerald;amount:%random1,%random3,5%%;name:&7&k..&r &5&lSharded &2&lEmerith&r &7&k..;lore:<{\"text\":\"\\u00A7bUseful for getting more\"}>,<{\"text\":\"\\u00A77RTPs \\u00A7band \\u00A77Claim Blocks\\u00A78!\"}>;tags:shopItem:yes,serverItem:yes;"